const mycorpus = [
  `The one overwhelming piece of feedback I've seen about the new iPhone 16 is that it looks pretty. The new teal, ultramarine, and pink colors are more vivid than previous ones, thanks to a new manufacturing process, which Apple says infuses color throughout the glass back of the phone. The iPhone 16 Pro colors are boring, and I agree.
  There are no sweeping changes to the iPhone 16 over its predecessor. Yes, there's a new Camera Control button, and the Action Button has trickled down from the Pro, but nearly every other part of the device is an iterative upgrade. I've also now been living with Apple Intelligence for a few weeks—at least, a beta version of it with some missing features—and it's safe to say that while there are a few features that will be very helpful day-to-day for some folks, it is not a reason to upgrade, especially if your iPhone is functioning fine.
  All that said, this iPhone has a beefier battery and a more powerful processor, and it is easier to repair. Its cameras are more than capable. Combined with the fact that Face ID is still unrivaled, the Dynamic Island has grown on me, and I'm still waiting for MagSafe-like charging to make its way to Android phones. It doesn't feel like the iPhone 16 needs much more. Apple spends a lot of time on prosumer features in its iPhone Pro models, but very few people will use them. ProRes? Log video recording? Academy Color Encoding System? If none of those words matter to you, then there are only a few reasons to get the iPhone 16 Pro this year.
  The main things have to do with the display. The iPhone 16 Pro models have bigger screens now, one-upping the 6.1-inch and 6.7-inch OLED screens on the iPhone 16 and iPhone 16 Plus. This change is more effective on the iPhone 16 Pro, but it makes the iPhone 16 Pro Max too unwieldy. The screen sizes on the non-Pro iPhones never leave me wanting. On the non-Pro iPhone, you don't have the always-on display, but I don't mind that it's not here. Apple's more serious omission is the lack of ProMotion on the cheaper iPhones. This means you are stuck on a 60-Hz screen when almost every other smartphone at this price has a 120-Hz refresh rate. Maybe I'm nitpicking, but the first thing I said after switching from the iPhone 16 Pro to the iPhone 16 was, “Why is it laggy?” It's not that the phone performs poorly. The display refreshes 60 times per second, and when you move from screens that refresh 120 times, you're effectively seeing slower animations throughout. This tech will likely get ported down in 2025, but it's past due at this price.
  The entire iPhone 16 lineup has Apple's new Ceramic Shield glass, which is supposedly twice as strong as the previous generation, but remember: Glass is still glass. I dropped the iPhone 16 Plus onto the pavement (a 4-foot drop), and the display cracked; business as usual. Get a case and screen protector! Build-wise, the Pro phones have a titanium frame versus aluminum on the standard iPhones, but durability-wise, they're all glass sandwiches. Titanium does make the Pro phones lighter, but the iPhone 16 and 16 Plus still weigh less.
  Camera Control is the new button on the iPhone 16 range, and I'm getting used to it. I prefer to use it as a dedicated camera launch button, freeing up the Action Button (also new on a non-Pro iPhone) to trigger something else, like Silent mode. But you can put some light pressure on the Camera Control button to cycle through camera modes or scroll through different Photographic Styles—the revamped color-grading filters that let you add a look to your images pre-capture. I use the sliding function here and there but prefer to select the mode I want to shoot in by tapping the screen. In recent years, Apple started giving the iPhone Pro models a significant chip upgrade to increase the performance gap between the phones, but this year they're all on the same starting point: the A18 chipset. The iPhone 16 Pro devices have the A18 Pro, which features larger CPU cache sizes and an extra graphics core for slightly better overall performance. That said, in my benchmark tests, the iPhone 16 and iPhone 16 Plus are just behind the Pros and still more powerful than any other phone on the market.
  I played AAA games like Resident Evil and Assassin's Creed Mirage, though I did run into a few more stutters than on the Pro models (and just as many crashes, though this could have been because I was running a developer beta of iOS 18.1). I want to note that these games are currently the cream of the crop in graphical fidelity, so I'm purposefully stress-testing. Most of the titles you'll play will run perfectly. The Pro models this year have improved thermal performance, but Apple made some tweaks to improve the heat dissipation on the standard iPhones too, and I have not noticed the phones getting significantly hot.
  If you buy something using links in our stories, we may earn a commission. This helps support our journalism. Learn more. Please also consider subscribing to WIRED More importantly, every iPhone 16 model will be capable of running Apple Intelligence, the suite of artificial intelligence features coming in an update in October. I go over exactly what's included in Apple Intelligence in my iOS 18 guide, and have broadly evaluated the current experience in my iPhone 16 Pro review. There are some helpful day-to-day features, like real-time transcriptions in Voice Notes or call recordings, but we'll have to wait until Apple brings the full kit.
  Battery life is a high note. I eked out better battery life on the iPhone 16 Plus than on the Pro Max, hitting more than seven hours of screen-on time with 36 percent left in the tank at 1 am. The iPhone 16 is no slouch, giving me six hours of screen-on time with around 20 percent remaining. And that's with a mix of doomscrolling on Instagram, picture-snapping, navigation, and music streaming. These devices will get you through a full day and then some. Speaking of the battery, it's easier to replace on the iPhone 16 and 16 Plus (not the Pro models), and iFixit gave it a 7/10 in overall repairability, which is a huge improvement over prior years.
  It's a shame Apple did not bring an updated spec for the charging port. When Apple switched to USB-C last year, it kept the same data transfer speeds for the iPhone 15—480 megabits per second. The Pro, on the other hand, has USB3 speeds of up to 20 gigabits per second. It's a massive difference (and an unnecessary one), but this only matters if you find yourself moving files from your iPhone to another device with a cord.
  The iPhone 16 and iPhone 16 Plus hold their own in the camera department. I found no significant differences even in low light when shooting with the main camera and the ultrawide. The Pro phones edge them out here and there, but the gap is small. Autofocus is new in the 12-MP ultrawide, so you can take macro photos. I can't stop taking close-up shots of my pup's nose. Boop!
  I do miss the telephoto camera, and that is the number one reason to buy a Pro iPhone. You get a 2X zoom on the iPhone 16 and iPhone 16 Plus, and the quality is OK, but it's not as satisfying as the 5X optical zoom on the iPhone 16 Pro and Pro Max. Their cameras can capture much sharper photos of subjects further away.
  `,
  `
    For years now, the best iPhones have featured a $200 spread between the standard and Pro models, so I’m always faced with trying to make an argument to go with the less expensive model. That’s why I’m hyper-focused on inspecting every little detail with my iPhone 16 review, mainly because I want you to know what exactly you’re getting (or compromising) by choosing this less expensive handset over the iPhone 16 Pro.
  I know a lot of people are always torn over which iPhone to get, but the models making up this year’s iPhone 16 lineup have a lot more in common than years past. For example, the iPhone 16 gains the Action button that was first exclusive to the iPhone 15 Pros last year and the same Camera Control button found in the iPhone 16 Pros. It even shares just about the same set of Apple Intelligence features (which will come post release as a software update to iOS 18).
  One of the biggest questions I also want to answer in my iPhone 16 review is how this model's upgraded cameras compare to last year’s iPhones, along with the pricier iPhone 16 Pro and its main competitors in the space. 
  Every year I find myself holding my breath until Apple announces the prices of its new iPhones. Luckily, this happens to be a year in which there are no price hikes for the base iPhone 16, which starts at $799. Preorders for the iPhone 16 are available right now, with full availability starting on September 20.
  The iPhone 16 will be available in three storage options: 128GB, 256GB, and 512GB, which have been the configurations for the last few years now. What I’m happy about this year are the brighter, more vibrant color options: pink, teal, ultramarine, black, and white. These new colorways are enchanting, and possibly enough to sway people from going with the iPhone 16 Pros because they’re bolder looking than the pastel-like colors of the iPhone 15.
  There’s something to say about using a smaller sized phone. While there’s no size change between the iPhone 15 and this year's standard model, the iPhone 16 is a smidge lighter at 6 ounces, making the phone a breeze to use one-handed. It's certainly much easier to do so than with the larger iPhone 16 Pro and 16 Pro Max models. For the iPhone 16, Apple leverages aerospace-grade aluminum with its design, which not only makes it lighter, but also more durable.
  However, as much as Apple claims that the latest-generation Ceramic Shield glass is tougher and more resilient, my review unit got noticeably scratched up just after a few times stuffed in my bag. And this is why I can’t stress enough about installing a screen protector and any of the best iPhone 16 cases if you want to keep your new phone's pristine looks intact.
  Despite that, the iPhone 16 is a much more stylish phone than the iPhone 16 Pros, which is a shame because I’d love to see these bolder colors come to the Pro iPhones. I also love how the color-infused back glass with my ultramarine colorway review unit pops at just the right angle, while small details like the outline color of the rear cameras makes for a strong contrast as an accent color.
  Speaking of cameras, that’s one of the many new design changes with the iPhone 16. Instead of the diagonal arrangement that the series has been using for the last three years, it’s been reverted to a vertical arrangement to allow support for Spatial video and photo capture. Other new changes to the design include the Action Button on the left side of the phone and the Camera Control on the right. And finally, the USB-C port found on the bottom of the iPhone 16 is still stuck on slower USB 2.0 speeds that the iPhone 15 offered.
  Nevertheless, the addition of these features along with its charming looks add to the iPhone 16 design, as well as narrowing the gap in what it can functionally do compared to the iPhone 16 Pro.
  In contrast to the iPhone 16 Pro, there’s no change to the screen size on the new iPhone 16, it’s still a 6.1-inch Super Retina XDR display with a resolution of 2,556 x 1,179 pixels. Also, the same cutout near the top for its Dynamic Island doesn’t change in size.
  Visually the display doesn’t disappoint. It’s a pleasant looking OLED panel that gets the job done for most things. I pulled up the Rings of Power Season 2 trailer, and I like how the iPhone 16 display has just enough saturation and contrast to make some of the scenes pop. However, I’m still very critical about Apple’s decision to keep the display refresh rate to 60Hz on its less expensive flagships, which is disappointing given how much cheaper phones have better refresh rates.
  Most people probably won’t care, but I’ve seen how the faster 120Hz refresh rate on the cheaper Pixel 8a smooths out motion to make action scenes look more fluid. As a result of its 60Hz display, the iPhone 16 doesn’t have the same slick-smoothing animation as other phones.
  Putting the iPhone 16 through Tom’s Guide’s display benchmark test, Apple's new phone comes up a little short at 1,348 nits — which is down from the 1,401 nit brightness of the iPhone 15. It’s not a terrible difference, but given how Apple again claims up to a 3,000 nit rating, I was hoping for at least an improvement in this area. But despite this, I will say that none of this affects the iPhone 16's screen visibility outdoors. It’s usable, but it definitely benefits from a shade with my hand outside.
  The Camera Control button is positioned on the right side of the iPhone 16 and can recognize the amount of pressure applied to it — thus replicating the physical shutter button commonly found in today’s best mirrorless cameras. I will say that the Camera Control takes a bit getting used to because of the extra functions you’ll have access to.
  While pressing it down all the way allows you to take a photo, pressing and holding on the button initiates video recording. I do like how the Camera Control can also discern swipes to change between some of the settings, like zoom controls, exposure adjustment, and more — all by slightly pressing the Camera Control button and swiping my finger left or right. Though it may take a bit getting used to all of this, it’s a step in the right direction in making the iPhone feel more like a camera.
  However, I still wish Apple added more controls — like access to the shutter speed and ISO, which could help enthusiasts like myself to get more out of the phone's camera. In terms of audio recording, the iPhone 16 and 16 Plus also gain the same Audio Mixing feature that lets shooters adjust the sound of the audio after a video's recorded. This was previously introduced as a feature for the iPhone 16 Pro and iPhone 16 Pro Max, but it's been confirmed to be available on the standard iPhone 16 models.
  Just as before, the iPhone 16 and 16 Plus feature dual rear cameras that consist of a 48MP main shooter and a refreshed 12MP ultrawide. That latter certainly gets more attention this time around because the series finally gains the ability to capture macro photographs, which is a capability that has been limited to the Pro models.
  Apple also talks a lot about the versatility of this new camera setup, since it can effectively deliver photos with optical quality without a dedicated zoom camera — all by leaning on the same pixel-binning techniques I’ve seen previously with the iPhone 15 to get usable 2x zoom photos.
  Since the iPhone 16’s camera is very similar to the one in the iPhone 16 Pro/16 Pro Max, it’s worth seeing how it compares. In the shot above in downtown Half Moon Bay, the iPhone 16 pulls up a nice shot with just as much detail in the trees, parked cars, and signages around the street. The only advantage for the iPhone 16 Pro is how it produces a brighter image by increasing the exposure in the shadows. 
  One of the few changes to the iPhone 16’s cameras pertain to its refreshed 12MP ultrawide camera, which boasts a wider f/2.2 aperture lens (up from the iPhone 15’s f/2.4 one). Against the Pixel 9, it does bring out more detail in the shadowed areas in the tree on the left side, but the green leaves don’t look as vibrant as the Pixel. 
  Yet again, the iPhone 16 makes a strong case for being one of the best camera phones around because these selfie shots I captured of myself above are nearly identical when it comes to the details. Not only does it capture a lot of my facial features, like my hairline and beauty marks, but it also captures the same details with the background. The only difference is how the iPhone 16 Pro’s shot looks brighter. 
  Despite lacking a dedicated telephoto camera, the 2x zoom with the iPhone 16 still delivers good results. It matches the Galaxy S24 Plus at 2x zoom, with both capturing the details of the tree’s branches and bark. I’m also impressed by the effectiveness of pixel binning in the iPhone 16 because at 10x zoom, it comes close to matching the S24 Plus — and that’s superb when you figure that the S24 Plus is using a 3x optical zoom. 
  `,
];

module.exports = mycorpus;
